# Generated by Django 4.2.6 on 2023-11-06 17:32

import app_cad_usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0003_rename_id_usuarios_usuario_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default=app_cad_usuarios.models.default_password, max_length=128),
        ),
    ]
